custom_components/hikvision_next/isapi.py
https://github.com/maciej-or/hikvision_next/issues/3
=> ISAPI v1.0 fixes

custom_components/hikvision_next/translations/pt-BR.json
Please, Add Brazilian Portuguese Translation
=> Add Brazilian Portuguese Translation

README.md, custom_components/hikvision_next/manifest.json
https://github.com/maciej-or/hikvision_next/issues/44
https://github.com/maciej-or/hikvision_next/issues/47
=> release v1.0.5

custom_components/hikvision_next/isapi.py
=> obtaining RTSP port from device settings

custom_components/hikvision_next/isapi.py
=> hdd list fix

custom_components/hikvision_next/binary_sensor.py, custom_components/hikvision_next/camera.py, custom_components/hikvision_next/diagnostics.py, custom_components/hikvision_next/isapi.py, custom_components/hikvision_next/notifications.py
@maciej-or a number of updates to fix issues and minor bugs.
1. Fix issue in reported firmware on a camera device - issue #67 
2. Modified the way binary sensors are notified of an event to have each sensor listening for a boradcast and determine if it is for it.  The trigger_sensor then dispatches an event when a hikvision event comes in.  Each binary sensor will change its state for 5 seconds to show event detected and then revert.  This allows changing of entity name without issue.  I also added PR #77 into this to prevent a merge conflict. Fixes issue #61 
3. Corrected the name of the camera entity to include the camera name and stream type - issue #73 
4. Corrected an error on CameraStreamInfo object where stream type was incorrectly set.
5. Corrected an issue in diagnostics whereby …
=> Multiple Updates

custom_components/hikvision_next/isapi.py
=> skip events with eventType None

README.md
I've been working with this integration for a while now.
I can confirm that the following devices are working well with this integration:
- DS-7608NI-I2
- DS-2CD2087G2-LU
- DS-2CD2T87G2-L
The devices are inserted into the list in alphabetical order.
=> doc: added 3 more supported devices (tested for a while)

custom_components/hikvision_next/__init__.py, custom_components/hikvision_next/config_flow.py, pyproject.toml
Sets unique id as string and migrates invalid old
=> fix for Home Assistant 2024.2.0 crash

custom_components/hikvision_next/__init__.py, custom_components/hikvision_next/isapi.py
fixes https://github.com/maciej-or/hikvision_next/issues/151 and https://github.com/maciej-or/hikvision_next/issues/132
=> supress http errors to not break device initialization flow

custom_components/hikvision_next/isapi.py, custom_components/hikvision_next/manifest.json
fixes https://github.com/maciej-or/hikvision_next/issues/167
=> hotfix for devices without alarm server

README.md, custom_components/hikvision_next/binary_sensor.py, custom_components/hikvision_next/camera.py, custom_components/hikvision_next/const.py, custom_components/hikvision_next/sensor.py, custom_components/hikvision_next/switch.py, custom_components/hikvision_next/translations/en.json, custom_components/hikvision_next/translations/pl.json, tests/test_camera.py
- added entities translation support
- added translations for english and polish
=> entities translation support

custom_components/hikvision_next/binary_sensor.py, custom_components/hikvision_next/coordinator.py, custom_components/hikvision_next/diagnostics.py, custom_components/hikvision_next/isapi.py, custom_components/hikvision_next/switch.py, tests/fixtures/devices/DS-2CD2386G2-IU.json, tests/test_init.py
https://github.com/maciej-or/hikvision_next/issues/98
=> fix for scene change event entities for newer ipc firmware

README.md, custom_components/hikvision_next/__init__.py, custom_components/hikvision_next/binary_sensor.py, custom_components/hikvision_next/coordinator.py, custom_components/hikvision_next/diagnostics.py, custom_components/hikvision_next/isapi.py, custom_components/hikvision_next/switch.py, tests/fixtures/devices/DS-2CD2386G2-IU.json, tests/fixtures/devices/DS-7616NI-Q2.json, tests/test_camera.py, tests/test_init.py, tests/test_switch.py
https://github.com/maciej-or/hikvision_next/issues/79
=> disable entities for events without notifications

custom_components/hikvision_next/__init__.py
fixes https://github.com/maciej-or/hikvision_next/issues/187
=> loading integration fix

custom_components/hikvision_next/const.py, custom_components/hikvision_next/isapi.py, tests/fixtures/ISAPI/EventNotificationAlert/pir.xml, tests/fixtures/devices/DS-2CD2443G0-IW.json, tests/test_init.py, tests/test_pir.py
please test PIR sensor and switch on single camera and connected to NVR.
=> added pir support

custom_components/hikvision_next/__init__.py, custom_components/hikvision_next/isapi.py, custom_components/hikvision_next/isapi_client.py, custom_components/hikvision_next/manifest.json, requirements.test.txt
=> api client with non blocking calls

custom_components/hikvision_next/isapi.py, tests/fixtures/devices/DS-2CD2532F-IWS.json, tests/test_init.py, tests/test_pir.py
=> improved pir support detection #220

custom_components/hikvision_next/coordinator.py, custom_components/hikvision_next/switch.py
=> support for renaming entity id

custom_components/hikvision_next/__init__.py, custom_components/hikvision_next/const.py, custom_components/hikvision_next/image.py, custom_components/hikvision_next/isapi.py, custom_components/hikvision_next/services.py, custom_components/hikvision_next/services.yaml, tests/test_pir.py, tests/test_services.py, tests/test_switch.py
=> added reboot service

custom_components/hikvision_next/config_flow.py, custom_components/hikvision_next/hikvision_device.py, custom_components/hikvision_next/translations/en.json, custom_components/hikvision_next/translations/pl.json, tests/conftest.py
for self signed certificate leave it unchecked
#230, #124
=> verify SSL option for self-signed certs

custom_components/hikvision_next/__init__.py
=> migration fix

custom_components/hikvision_next/isapi/isapi.py, tests/fixtures/devices/DS-7608NXI-I2.json, tests/fixtures/devices/DS-7732NI-M4.json, tests/test_camera.py
=> workaround for proxy cameras with repeated serial no
